- name: CentOS-8 Comes with MySQL 8 Version by default, However our application needs MySQL 5.7. So lets disable MySQL 8 version.
  ansible.builtin.shell: dnf module disable mysql -y
- name: copying mysql.repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
- name: installing mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: present
- name: starting and enabling mysqld
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes
- name: setting up the password for mysql
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('amazon.aws.aws_ssm', 'mysql-{{env}}.DB_PASS', region='us-east-1' ) }}
