- name: copy the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy alert-rules from common
  ansible.builtin.template:
    src: common.yml
    dest: /opt/prometheus/alert-rules/common.yml

- name: restart the prometheus
  ansible.builtin.shell: kill 1 $(ps -ef | grep /opt/prometheus/prometheus | grep -v grep | awk '{print $2}')

- name: Copy AlertManager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart the AlertManager
  ansible.builtin.shell: kill 1 $(ps -ef | grep /opt/alertmanager/alertmanager | grep -v grep | awk '{print $2}')


