- name: copy the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy alert-rules
  ansible.builtin.template:
    src: common.yml
    dest: /opt/prometheus/alert-rules/common.yml

- name: list the all files in the bucket
  amazon.aws.s3_object:
    bucket: prometheus-frontend-alert-file
    mode: list
  register: out

- name: Download All objects from s3 bucket having alert files to download to prometheus
  amazon.aws.s3_object:
    bucket: prometheus-frontend-alert-file
    mode: get
    object: "{{ item }}"
    dest: /opt/prometheus/alert-rules/{{ item }}
  loop: "{{ out.s3_keys }}"

- name: reload the prometheus
  ansible.builtin.shell: kill 1 $(ps -ef | grep /opt/prometheus/prometheus | grep -v grep | awk '{print $2}')

- name: copy alertmanager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: reload the alertmanager
  ansible.builtin.shell: kill 1 $(ps -ef | grep /opt/alertmanager/alertmanager | grep -v grep | awk '{print $2}')


