- name: copy the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy alert-rules
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /opt/prometheus/alert-rules.yml

- name: restart the prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: Copy AlertManager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart the AlertManager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    enabled: yes

