groups:
- name: {{ component }}-{{ dev }}
  rules:
  - alert: CPUUsageAlert
    expr: avg by (instance) ((1 - rate(node_cpu_seconds_total{mode="idle"}[5m])) *100)
    for: 1m
    labels:
      severity: warning
      component: {{ component }}
      env: {{ env }}
    annotations:
      summary: warning | CPU down alert